-- INSERT INTO `tasks` (`title`) VALUES ("sample-task-01");
-- INSERT INTO `tasks` (`title`) VALUES ("sample-task-02");
-- INSERT INTO `tasks` (`title`) VALUES ("sample-task-03");
-- INSERT INTO `tasks` (`title`) VALUES ("sample-task-04");
-- INSERT INTO `tasks` (`title`, `is_done`,`priority`) VALUES ("sample-task-05", true,3);
-- INSERT INTO `tasks` (`title`, `is_done`,`priority`,`deadline`) VALUES ("sample-task-06", true,3,'2022-12-22 16:09:10');
-- INSERT INTO `tasks` (`title`, `is_done`,`priority`,`deadline`) VALUES ("sample-task-07", true,3,'2022-12-23 16:09:10');
-- INSERT INTO `tasks` (`title`, `is_done`,`priority`,`deadline`) VALUES ("sample-task-08", true,3,'2022-12-24 16:09:10');